server:
  port: 8888

grpc:
  server:
    port: 50051

spring:
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  prefix: 'Bearer '
  access-token-header: Authorization
  secret: ${SECRET_KEY}
  access-token-TTL: 300
  refresh-token-TTL: 259200

cookie:
  refresh-token:
    cookie-name: Refresh
    limit-time: 259200
    accepted-url: /api/members/refresh_token
    domain: ${COOKIE_DOMAIN}
    http-only: true
